concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
session_timeout = 1800

[[runners]]
name = "5ada7dc7be1a"
url = "http://gitlab.codicam.com/"
clone_url = "http://gitlab.codicam.com/"
id = 5
token = "6JZ7JoLy4vKDqTkV_6_1"
token_obtained_at = 2023-02-07T20:55:25Z
token_expires_at = 0001-01-01T00:00:00Z
executor = "docker"
pre_get_sources_script = "git config --global http.proxy $HTTP_PROXY; git config --global https.proxy $HTTPS_PROXY"
environment = []
[runners.custom_build_dir]
[runners.cache]
MaxUploadedArchiveSize = 0
[runners.cache.s3]
[runners.cache.gcs]
[runners.cache.azure]
[runners.docker]
tls_verify = false
image = "alpine:latest"
privileged = false
disable_entrypoint_overwrite = false
oom_kill_disable = false
disable_cache = false
volumes = ["/cache"]
shm_size = 0
