version: '3.7'

services:

  gitlab:

    image: 'gitlab/gitlab-ce:latest'
    networks:
      - traefik
    restart: always
    hostname: 'gitlab.codicam.com'

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        
        # ---------- GENERAL GITLAB CONFIG ---------- #
        
        external_url 'https://gitlab.codicam.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['lfs_enabled'] = true
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        
        # ---------- GITLAB REGISTRY CONFIG ---------- #
        
        registry_external_url 'https://registry.gitlab.codicam.com'
        registry_nginx['listen_port'] = 80
        registry_nginx['listen_https'] = false
        registry['enable'] = true

    ports:
      - '8929:80'
      - '2224:22'
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    shm_size: '256m'

    labels:

      # ---------- TRAEFIK GLOBAL GITLAB CONFIG ---------- #

      - "traefik.enable=true"

      - "traefik.http.routers.gitlab.rule=Host(`gitlab.codicam.com`)"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"

      - "traefik.http.routers.gitlab.entrypoints=web"

      - "traefik.http.routers.gitlab-secure.rule=Host(`gitlab.codicam.com`)"
      - "traefik.http.routers.gitlab-secure.entrypoints=websecure"
      - "traefik.http.routers.gitlab-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.gitlab-secure.middlewares=test-compress,test-errorpages"

      - "traefik.http.routers.gitlab.service=gitlab"

      # Headers
      - 'traefik.http.routers.gitlab-secure.middlewares=gitlab-headers'
      - 'traefik.http.middlewares.gitlab-headers.headers.customrequestheaders.X_FORWARDED_PROTO=https'
      - 'traefik.http.middlewares.gitlab-headers.headers.customrequestheaders.X_Forwarded-Ssl=on'
      - 'traefik.http.middlewares.gitlab-headers.headers.customresponseheaders.X_FORWARDED_PROTO=https'
      - 'traefik.http.middlewares.gitlab-headers.headers.customresponseheaders.X_Forwarded-Ssl=on'

      # Error Pages Middleware
      - "traefik.http.middlewares.test-errorpages.errors.status=400-599"
      - "traefik.http.middlewares.test-errorpages.errors.service=error"
      - "traefik.http.middlewares.test-errorpages.errors.query=/{status}.html"

      # Compress Middleware
      - "traefik.http.middlewares.test-compress.compress=true"

      # Redirect Scheme HTTP -> HTTPS
#      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"

      # ---------- TRAEFIK GITLAB REGISTRY CONFIG ---------- #

      - "traefik.http.routers.registry-secure.rule=Host(`registry.gitlab.codicam.com`)"
      - "traefik.http.routers.registry-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.registry-secure.entrypoints=websecure"
      - "traefik.http.routers.registry.service=registry"


  gitlab-runner:

    image: 'gitlab/gitlab-runner:latest'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gitLab-runner/config:/etc/gitlab-runner
    restart: always


networks:
  traefik:
    name: traefik
    driver: bridge
